INSERT INTO flowers (name, color)
VALUES
    ('Rose', 'Red'),
    ('Tulip', 'Yellow'),
    ('Sunflower', 'Yellow'),
    ('Daisy', 'White'),
    ('Lily', 'White'),
    ('Orchid', 'Purple'),
    ('Hydrangea', 'Blue'),
    ('Peony', 'Pink'),
    ('Gerbera Daisy', 'Orange'),
    ('Iris', 'Blue'),
    ('Carnation', 'Pink'),
    ('Lavender', 'Purple'),
    ('Daffodil', 'Yellow'),
    ('Marigold', 'Orange'),
    ('Poppy', 'Red'),
    ('Violet', 'Purple'),
    ('Chrysanthemum', 'Yellow'),
    ('Zinnia', 'Red'),
    ('Snapdragon', 'Pink'),
    ('Foxglove', 'Pink'),
    ('Bleeding Heart', 'Pink'),
    ('Calla Lily', 'White'),
    ('Black-eyed Susan', 'Yellow'),
    ('Anemone', 'White'),
    ('Pansy', 'Purple');
